services:
  db:
    image: postgres:16.4-bullseye
    ports:
      - "5433:5432"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env

  client:
    build:
      context: ./to-do-app
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    env_file:
      - .env